name: Write__Adapt__
title: WriteAdapt - For People Who Love Content
org: Strategy Media
author: The Octocat
author_url: https://github.com/octocat
base_url: ''
ctx_path: ''
interpolate: false
haml:
    :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://clonezone.github.io/writeadapt-clonezone
    ctx_path: /writeadapt-clonezone
    asciidoctor:
      :attributes:
        base_url: http://clonezone.github.io/writeadapt-clonezone
        ctx_path: /writeadapt-clonezone
        # imagesdir must be absolute to work around Atom feed bug
        imagesdir: http://clonezone.github.io/writeadapt-clonezone/images
    deploy:
      host: github_pages
      branch: gh-pages
